# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/ingestion/telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/ingestion/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsrc/ingestion/telemetry.proto\x12\x12sentinel.telemetry\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n\x10VehicleTelemetry\x12\x0b\n\x03vin\x18\x01 \x01(\t\x12.\n\nevent_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12=\n\x07metrics\x18\x03 \x01(\x0b\x32,.sentinel.telemetry.VehicleTelemetry.Metrics\x1aH\n\x07Metrics\x12\x15\n\rengine_temp_f\x18\x01 \x01(\x01\x12\x11\n\tspeed_kmh\x18\x02 \x01(\x05\x12\x13\n\x0b\x62\x61ttery_soc\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.ingestion.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLETELEMETRY']._serialized_start=87
  _globals['_VEHICLETELEMETRY']._serialized_end=303
  _globals['_VEHICLETELEMETRY_METRICS']._serialized_start=231
  _globals['_VEHICLETELEMETRY_METRICS']._serialized_end=303
# @@protoc_insertion_point(module_scope)
